// Pure preset-question data — NO imports, so functions/api/suggest.ts can
// bundle it without dragging OpenCC into the worker. zh-tw derives in
// ask-presets.ts (build-time only). Keep every question answerable from
// the qa-corpus digest.

export type AskPresetLang = 'zh' | 'en' | 'ja' | 'ko';

export const ASK_PRESET_DATA: Record<AskPresetLang, string[]> = {
  zh: [
    '新加坡的国家 AI 战略 NAIS 2.0 讲了什么？',
    '和其他国家比，新加坡 AI 的独特优势在哪里？',
    '新加坡怎么监管生成式 AI 和 deepfake？',
    '国会最近在辩论哪些 AI 议题？',
    'SEA-LION 是什么？下载量怎么样？',
    '新加坡 AI 人才有哪些培养计划？',
    '新加坡政府每年在 AI 上花多少钱？',
    '新加坡有哪些 AI 独角兽和明星创业公司？',
    'AI Verify 是什么？企业怎么用它？',
    '新加坡的算力基建（数据中心、超算）是什么水平？',
    '杨莉明在 AI 政策上的角色是什么？',
    '新加坡怎么应对 AI 带来的失业风险？',
    '淡马锡在 AI 上的投资策略是什么？',
    '新加坡和美国、中国的 AI 治理路线有什么不同？',
    '中小企业在新加坡能拿到哪些 AI 补贴？',
    'IMDA 和 AI Singapore 各自负责什么？',
    '新加坡 AI 相关的法律有哪些？版权怎么算？',
    'IOAI 2027 是什么？为什么在新加坡办？',
  ],
  en: [
    'What is Singapore’s National AI Strategy 2.0 (NAIS 2.0)?',
    'What makes Singapore’s AI strategy different from other countries?',
    'How does Singapore regulate generative AI and deepfakes?',
    'What AI topics has Parliament debated recently?',
    'What is SEA-LION and how widely is it used?',
    'What AI talent programmes does Singapore run?',
    'How much does the Singapore government spend on AI each year?',
    'Which AI unicorns and standout startups does Singapore have?',
    'What is AI Verify and how do companies use it?',
    'How strong is Singapore’s compute infrastructure (data centres, supercomputers)?',
    'What is Josephine Teo’s role in Singapore’s AI policy?',
    'How is Singapore handling AI-driven job displacement?',
    'What is Temasek’s AI investment strategy?',
    'How does Singapore’s AI governance differ from the US and China?',
    'What AI subsidies can SMEs get in Singapore?',
    'What do IMDA and AI Singapore each do?',
    'What AI-related laws does Singapore have? How is copyright handled?',
    'What is IOAI 2027 and why is Singapore hosting it?',
  ],
  ja: [
    'シンガポールの国家 AI 戦略 NAIS 2.0 とは何ですか？',
    '他国と比べたシンガポール AI の強みはどこですか？',
    'シンガポールは生成 AI やディープフェイクをどう規制していますか？',
    '国会では最近どんな AI 議題が討論されていますか？',
    'SEA-LION とは何ですか？どのくらい使われていますか？',
    'シンガポールにはどんな AI 人材育成プログラムがありますか？',
    'シンガポール政府は毎年 AI にいくら投資していますか？',
    'シンガポールにはどんな AI ユニコーンや注目スタートアップがありますか？',
    'AI Verify とは何ですか？企業はどう使いますか？',
    'シンガポールの計算インフラ（データセンター、スパコン）はどの水準ですか？',
    'ジョセフィン・テオは AI 政策でどんな役割を担っていますか？',
    'シンガポールは AI による雇用喪失にどう対応していますか？',
    'テマセクの AI 投資戦略はどんなものですか？',
    'シンガポールの AI ガバナンスは米国や中国とどう違いますか？',
    '中小企業はシンガポールでどんな AI 補助金を受けられますか？',
    'IMDA と AI Singapore はそれぞれ何を担当していますか？',
    'シンガポールの AI 関連法にはどんなものがありますか？著作権はどう扱われますか？',
    'IOAI 2027 とは何ですか？なぜシンガポールで開催されますか？',
  ],
  ko: [
    '싱가포르의 국가 AI 전략 NAIS 2.0은 어떤 내용인가요?',
    '다른 나라와 비교해 싱가포르 AI의 강점은 무엇인가요?',
    '싱가포르는 생성형 AI와 딥페이크를 어떻게 규제하나요?',
    '국회에서 최근 어떤 AI 의제를 토론했나요?',
    'SEA-LION은 무엇이며 얼마나 사용되나요?',
    '싱가포르에는 어떤 AI 인재 양성 프로그램이 있나요?',
    '싱가포르 정부는 매년 AI에 얼마나 투자하나요?',
    '싱가포르에는 어떤 AI 유니콘과 주목할 스타트업이 있나요?',
    'AI Verify는 무엇이고 기업은 어떻게 활용하나요?',
    '싱가포르의 컴퓨팅 인프라(데이터센터, 슈퍼컴퓨터)는 어느 수준인가요?',
    '조세핀 테오는 AI 정책에서 어떤 역할을 하나요?',
    '싱가포르는 AI로 인한 일자리 충격에 어떻게 대응하나요?',
    '테마섹의 AI 투자 전략은 무엇인가요?',
    '싱가포르의 AI 거버넌스는 미국·중국과 어떻게 다른가요?',
    '중소기업은 싱가포르에서 어떤 AI 지원을 받을 수 있나요?',
    'IMDA와 AI Singapore는 각각 무엇을 담당하나요?',
    '싱가포르의 AI 관련 법에는 어떤 것이 있나요? 저작권은 어떻게 처리되나요?',
    'IOAI 2027은 무엇이며 왜 싱가포르에서 열리나요?',
  ],
};
